### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by itsyohan** [cirla/vim-giphy#1]
Hi,

I successfully ran brew install ffmpeg, but got stuck on the next step. 
When I added _Plugin 'mattn/webapi-vim'_ in my .vimrc file, I got this error:

`error detected while processing /Users/AYL/.vimrc:
line   27:
E492: Not an editor command: Plugin 'mattn/webapi-vim'
line   28:
E492: Not an editor command: Plugin 'cirla/vim-giphy'
Press ENTER or type command to continue`

I am not super familiar with vim; are there any steps in between that I am missing?

**Comment by cirla** [comment]
Hi,

For plugin management in vim, I use [Vundle](https://github.com/gmarik/Vundle.vim), which provides the `Plugin` command. 

Tim
